#!/bin/bash

echo ""
echo "This machine's private IP is: "
hostname --ip-address
echo ""

echo ""
echo "*  *  *  *  *  *  *  *"
echo ""
echo "$ docker swarm join [token_from_Manager]"
echo ""
echo "*  *  *  *  *  *  *  *"

echo ""
echo "Run next command after you have completed the setup on the Manager node"

echo ""
echo "$ curl http://[the_Managers_private-ip]"

echo ""
echo "*  *  *  *  *  *  *  *"
echo ""
